apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-tika
spec:
  selector:
    app: {{ .Values.appName }}-tika
  ports:
    - protocol: TCP
      port: 9998
      targetPort: 9998
  type: NodePort
  