apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-web
spec:
  selector:
    app: {{ .Values.appName }}-web
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8000
      name: web
  type: LoadBalancer
