---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{.Values.appName}}-push
  namespace: {{.Values.namespace}}
spec:
  encryptedData:
    pushId: AgBo1rYqLBO7CfOLrzao53+XsnKzgBdDRCAqjjON8SS8mMtCM6glQuqmwrNsi0P9epNICjcyiUejRYvulWH3Ki3w0wDUXTtBag50+miNOe6t7mRRAD3AiNkl4h+nrLX7plNMNN910B8KnlXjR+Pa0h+dVg61XjUAnoIBxRySQTYnMddHbyQN6lghFw/Lvinv4+HqwO9gG99yVttqN/2CEP1Ics+jOjtTy3pK27kivUpcWL4rJBO0zhsWQkxQRi0tWjVABqlL47h2NwNkCQYxGCz4nbKMzRx5xXj6FBPpUkm/InX0g0TwUy5a35s2fkGW05ygajxxnCFtHAhBA8/xOE+SYjFNcKVYWqIHGNR9QbATu016Ln8c1C/zUi5REFJxvSi8hH/mUoE5G7KyBQE2R3xkg4UzDReX8aoB4iaaksgKBlVtWNHmQ61esv+5ZQmyMcxeGi4HEVyyHt12cQy9U7Q4LzL84tXzOJhXr/7QMASe3+sGfhkYk+jGHfsYOCfpbr1ee3g57faQqFdNStQYIUVzCkzTNX43+BL4HsHLqRf5BzsELP0kAEDoonkwemKW3eR0wo7xrUdCOHWH6vI1s6Qk7UdtpIT2y2txWekbYF8j8zFZQmDiutukJ1kG7tgHbiN+YHkW7POFZi8fHopPAb0qU9l1q3gtZ/xodCfjA4jxvrnjbb1X8HG+hv/FW6Y3IS588kLi369WWxfl1IsbCBYiALl+2voK6EIlXxelfhHSbWKp97U=
    pushKey: AgAJY8vcG2opzbNVj4Zb87jeuYyUxaxKSemaMo2yceDnYRnYHn8+qCku9AFgyWySkBbT6115JQKTAtK+TxURGN0BnFy5O+u1fXuLPQB/cfFKGT8LnkyQNVwmuYQ6qCs+LsoPOTX1wK1yWjdPQBjL0ZE6yHCM4K8hePHAhd8icipJKRp3OUx7FQahe9v32OO0mI2osZftccxRCZzf7Qjn0LItmfCVzWlD/QD8mgKonyvD6Nc+lcNGbOHOP/o+Cd39a9hP8Rusf7noP2TPJ0as/LE4GAahNNBoXfZlLPgNTgeWDs0q5pmSVbZaUoMDNsrBWP7y9bE5DBLldXc2B55ejHCUdVpMwrtsCiDY8Qo/4HBM9Mu4Wqy9TgQT+jgUJaCSvx1OuCTJkeISYm2k5C8rjrNrIGbUUjlfTgTdPKKUZ0wIeQWz3DGOtQSeJGErlkiWpGxvOrj8/GFrO52AktEEsPnGkZYXiiUJ5UcvAOZINjxSTNXq9lw0IEewPg+Y2PiF0b3io8a7x0LGZOoGraw0+t1VNCrRf7XUuP78QolE5qYT6/PeQOcZMq2n/NwVRIpCJ8JzfitB+ojZXVAlSMmLhQXS/7uGeMbuvm/8lbLp6UWp000Fvkpp018x85shRjSPATSfM075hwX5AFVcUGgaHBzaGxsrqBoS7/GCq3djtMz0X3F88pyJEWK05lkOdgbN8IHkI4aE4QQ4yc4Ug0HfMEjKbEAVvg==
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: {{ .Values.appName }}
        meta.helm.sh/release-namespace: {{.Values.namespace}}
      creationTimestamp: null
      labels:
        app: {{.Values.appName}}
        app.kubernetes.io/managed-by: Helm
      name: {{.Values.appName}}-push
      namespace: {{.Values.namespace}}
    type: Opaque

