argocd:
    configs:
        secret:
            extra:
                oidc.keycloak.clientSecret: ENC[AES256_GCM,data:3C/KsWkZ4vPLwqYrqjGQhF4GgDWm89/n3NNncHPkhSA=,iv:9HOmEz5oAeTtRlc4OL76VqIxB8/cdIgBjNALU7NX5IM=,tag:0mFqgzZp7X/ghvX3k6buEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ykd38a4f2ax987t7zdqhvl3ncgyjqaxjngsqmlmnph8vnlx4hyxq4drs0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdThLUlJKV1hmTTFNeFM4
            MFVndTh4R2Y2alhrdWlmdHVUdnlKY29BVmpnCjVoUUpSMTJHdmxqakVtYWNaTWtM
            RmNDVzY1N0pNd1NTWDZZa09wTXlnbkEKLS0tIGNKMVpUa0Q0OTFVanhqa093dHBo
            SUpkMWdYcjBnZnFOcXBlRkZWMzhVNlUKmxxB35/GsoW3fe/5oJtRTv//Loxm+2GC
            3Lb3/BOK02pSZBsjKhLJNVqDRLweKmZGRI2q3lCs0ktifERkkAXnQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T21:49:47Z"
    mac: ENC[AES256_GCM,data:AYzgjDRFYr5u2eu+QmVX/zXdV1ZgE5mVAzJLu5l6TBsP2/yLcfa6bgIFW0szzZ+22rDe5TADigYeWJ/4dd4P1KXpGxfKl+BX1EpLNGAV6EHRIKQYybco8NNVhjsE9crkcLP2JGDLW5LLXOEvSsmPbaXHgbnRzCKWr/7kQ8spacw=,iv:2M+OT95PjQAWzlSPcSkSxsQIFnhTy7tJFXLHgACWa94=,tag:odsHFDQ+BUxHKni/StEebA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
