apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: {{.Values.name}}
    app.kubernetes.io/version: {{.Values.version}}
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Values.name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: {{.Values.name}}
        app.kubernetes.io/version: {{.Values.version}}
    spec:
      automountServiceAccountToken: true
      containers:
        - image: "{{.Values.image.repository}}:v{{.Values.version}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          name: {{.Values.name}}
          ports:
            - containerPort: 8080
              name: http-metrics
            - containerPort: 8081
              name: telemetry
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: {{.Values.name}}