apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-fritzbox-user
  labels:
    app: {{ .Values.appName }}
type: Opaque
data:
  user: cHJvbWV0aGV1cw==
  password: ZkFYaVVlaHFNZThIbWs=
