---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.appName }}-fritzbox-user
  labels:
    app: {{ .Values.appName }}
spec:
  encryptedData:
    password: AgB36kMmXSRD+MBin03nD28ohvIRprKpVyGieTtag9Lr5P4tKviK24VeyNhALU6afctG/m3Nr3GST/Ysvcu6KGY/7oojyOWDUghOfZ+/AaEpL6Yyli9x1xdxrj/0ZVDvo5FJmv1kWlaXmQoVtJfCVgoc5et4gQ70fO3szWjQ/VhjwwwQ89Jv2kZ4sw63pgSkxL9grPNiDxNd19pICYnelJWw7aszX11ZGehJPsyrk0oie0OP+2+Ad35ygYgH4bR2YtExTnfOM5j6cJqfqgD1LFtRK5EjT4C30daQ7i5XSNlC5SnHnaRMMiT1uc44Uo8/ZjcMiGNJV5ohfec5X/AfX9LKLls0NLCXeCllk5anyKomVV0NYWRegYxdPoDhphXYH/NSjXlzjKtM41ZR1hJrGcQuzmBthvB1LLXPyONFg179/cTnRTg9qyhH5QCqmDO09c9EUIKKBCwMFIX5EW8kXFT3sea0tk5n7VpLGrENxPQBDiPYUhi84N6lsRiPcHHuQorxPPhiyTfLHQ5oVRRr3e3KYGScpDmEjLju25tPSrmKZYSuux9wPmji6nUuJGDCsB7w9AWrb1hhLfcizGldAFUJ2wE72QCmvqh0zRQQNpxyXtxuh1xr+/1V0oUBiHB0F6bRRmzzpZ4CXIDc/Qlj/KlQH/ZJzTbwQ5uf7eXy7zmj4a3n3h7M8aGvGNOjOZMQoPGEQSJPR5GVMbxiUtXr+g==
    user: AgBjHuDDI2PwCm9MEz9O4y5Co99Vmj1xAPw/VkV1MwQhQgKQEp6BtK4u0vr+n+CgQ8/6YiKO+FbMQHJXRouZpZrSu8K/9NfUPcrt8EZjSXmhdLTxHzYrBi/XSZHSJ1WpFx1NSQVKE8M3Z0f4YBh4odps6FpXl+v9bEqSFohQBrOfrWtgif7+8Q3/yes00xd0B9x2LfxoNErOqI6SIsjsgJNTXyUAyJM2UsPHE0US4Yut2XTsMs7c3fHTXcy8gxv1XEkLf/nhNEKj6meyfaFM83a4QszsKCqrq1at8HhICxu8XHosL/Gtd++zom970cmbM6jHq4Fj+pq2hIjZxSXrPEiXpdZk1AzyzR6Mlpy1JD6PWwGWq8NusCwYOTiXbWmnwlB1xkeYX14umDztkp6+sp7HfNDkfwdSkxxVqaqk6auQ5bSWc8VfQpjapGlanEcuDUWAQ8yzURTUCH4yvqY7PcMZzgRSjkwTEu8VLuFqVMJrL+dlMevHXVO3XxhBcfMexkgD1ofNTjiIvPzAnubfzXx/vM0CJu1l9DMTrUMWa4fNTDMPCs8cKJeiDfdSxYWABJvq84iX/pBYKbsm4nbs2dXKNhhbBS9gx56308tFerdks+6+3RBkP9CpAhpmsfOupqvzkM26fBWNqvnKf9nPu2nqCPsijHAU4UsQxsyMrUpJgYnFinmTTkl923r6IpeKHoFgl28vn2IS5N4a
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: {{ .Values.appName }}
        meta.helm.sh/release-namespace: {{.Values.namespace}}
      creationTimestamp: null
      labels:
        app: {{ .Values.appName }}
        app.kubernetes.io/managed-by: Helm
      name: {{ .Values.appName }}-fritzbox-user
      namespace: {{.Values.namespace}}
    type: Opaque
