apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress-redirect
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: {{.Values.namespace}}-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: {{.Values.url}}
    - http:
        paths:
          - backend:
              service:
                name: {{ .Values.appName }}-service
                port:
                  number: 80
            pathType: ImplementationSpecific
            path: /