apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-service
spec:
  selector:
    app: {{.Values.name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  namespace: {{.Values.namespace}}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9100'
spec:
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
  ports:
    - name: node-exporter
      protocol: TCP
      port: 9100
      targetPort: 9100