apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
spec:
  selector:
    app: {{.Values.appName}}
  ports:
    - protocol: TCP
      port: 9787
      name: metrics
  type: ClusterIP
  