
replicaCount: 1
appName: homeassistant
namespace: homeassistant

ingress:
  hostnames:
    - path: home.jgdperl.com
      name: jgdperl
      enable: true
    - path: home.choffmann.io
      name: choffmann-io
      enable: true
    - path: home.choffmann.cloud
      name: choffmann-cloud
      enable: false

config:
  name: Twetder Feld 24
  baseUrl: home.jgdperl.com
  unit_system: metric
  timezone: Europe/Berlin
  config_path: /home/choffmann/k3s/homeassistant
  homekit:
    name: HomeAssistant Bridge
    port: 21063
    filter:
      include_entity_globs:
        - switch.lufter_badezimmer
        - switch.schlafzimmer_lampe_*
        - sensor.schlafzimmer_lampe_*
        - switch.schreibtisch_*
        - sensor.schreibtisch_*

image:
  repository: ghcr.io/home-assistant/home-assistant
  pullPolicy: IfNotPresent
  tag: 2023.12.3
