apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      name: {{ .Values.appName }}
      labels:
        app: {{ .Values.appName }}
    spec:
      hostNetwork: true
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.repository }}:{{.Values.image.tag}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /config
              name: homeassistant-pv
            - mountPath: /config/configuration.yaml
              subPath: configuration.yaml
              name: config
            - mountPath: /run/dbus
              name: bluetooth
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: {{.Values.appName}}-config
        - name: homeassistant-pv
          persistentVolumeClaim:
            claimName: {{.Values.appName}}-pvc
        - name: bluetooth
          hostPath:
            path: /run/dbus
