apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      name: {{ .Values.appName }}
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /config
              name: config
          env:
            - name: TZ
              value: {{ .Values.config.timezone }}
          ports:
            - containerPort: 8123
              name: default
            - containerPort: 1900
              name: discovery
            - containerPort: 21063
              name: homekit
            - containerPort: 5353
              protocol: UDP
              name: homekit-udp
            - containerPort: 5683
              name: coiot
            - containerPort: 5683
              name: coiot-udp
              protocol: UDP
      restartPolicy: {{ .Values.image.restartPolicy }}
      volumes:
        - name: config
          hostPath:
            path: {{ .Values.config.config_path }}
