apiVersion: v1
kind: Service
metadata:
  name: coiot-service-udp
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: UDP
      port: 5683
      targetPort: 5683
  type: LoadBalancer
  