apiVersion: v1
kind: Service
metadata:
  name: coiot-service
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 5683
      targetPort: 5683
  type: LoadBalancer

  