apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}-web
  labels:
    app: {{.Values.appName}}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.appName}}-web
  template:
    metadata:
      name: {{.Values.appName}}-web
      labels:
        app: {{.Values.appName}}-web
    spec:
      containers:
        - name: {{.Values.image.paperless.name}}
          image: {{.Values.image.paperless.repository}}:{{.Values.image.paperless.tag}}
          imagePullPolicy: {{.Values.image.paperless.pullPolicy}}
          ports:
            - containerPort: 8000
              hostPort: 8000
              name: web
          envFrom:
            - configMapRef:
                name: {{.Values.appName}}-configmap
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          env:
            - name: PAPERLESS_REDIS
              value: redis://{{.Values.appName}}-redis:6379
            - name: PAPERLESS_TIKA_ENABLED
              value: "1"
            - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
              value: http://{{.Values.appName}}-gotenberg:3000
            - name: PAPERLESS_TIKA_ENDPOINT
              value: http://{{.Values.appName}}-tika:9998
{{/*            - name: PAPERLESS_SECRET_KEY*/}}
{{/*              valueFrom:*/}}
{{/*                secretKeyRef:*/}}
{{/*                  name: secret-key*/}}
{{/*                  key: key*/}}
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: paperless-data
            - mountPath: /usr/src/paperless/media
              name: paperless-media
            - mountPath: /usr/src/paperless/export
              name: paperless-export
            - mountPath: /usr/src/paperless/consume
              name: paperless-consume
      restartPolicy: Always
      volumes:
        - name: paperless-data
          persistentVolumeClaim:
            claimName: {{.Values.appName}}-data
        - name: paperless-media
          persistentVolumeClaim:
            claimName: {{.Values.appName}}-media
        - name: paperless-consume
          persistentVolumeClaim:
            claimName: {{.Values.appName}}-consume
        - name: paperless-export
          persistentVolumeClaim:
            claimName: {{.Values.appName}}-export
