apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}-redis
  labels:
    app: {{.Values.appName}}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.appName}}-redis
  template:
    metadata:
      name: {{.Values.appName}}-redis
      labels:
        app: {{.Values.appName}}-redis
    spec:
      containers:
        - name: {{.Values.image.broker.name}}
          image: {{.Values.image.broker.repository}}:{{.Values.image.broker.tag}}
          imagePullPolicy: {{.Values.image.broker.pullPolicy}}
          ports:
            - containerPort: 6379
              hostPort: 6379
              name: redis
          volumeMounts:
            - mountPath: /data
              name: redisdata
      restartPolicy: Always
      volumes:
        - name: redisdata
          persistentVolumeClaim:
            claimName: {{.Values.appName}}-redis
