apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}-tika
  labels:
    app: {{.Values.appName}}-tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.appName}}-tika
  template:
    metadata:
      name: {{.Values.appName}}-tika
      labels:
        app: {{.Values.appName}}-tika
    spec:
      containers:
        - name: {{.Values.image.tika.name}}
          image: {{.Values.image.tika.repository}}:{{.Values.image.tika.tag}}
          imagePullPolicy: {{.Values.image.tika.pullPolicy}}
          ports:
            - containerPort: 9998
              hostPort: 9998
      restartPolicy: Always
