apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}-gotenberg
  labels:
    app: {{.Values.appName}}-gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.appName}}-gotenberg
  template:
    metadata:
      name: {{.Values.appName}}-gotenberg
      labels:
        app: {{.Values.appName}}-gotenberg
    spec:
      containers:
        - name: {{.Values.image.gotenberg.name}}
          image: {{.Values.image.gotenberg.repository}}:{{.Values.image.gotenberg.tag}}
          imagePullPolicy: {{.Values.image.gotenberg.pullPolicy}}
          ports:
            - containerPort: 3000
              hostPort: 3000
          command:
            - "gotenberg"
            - "--chromium-allow-list=file:///tmp/.*"
      restartPolicy: Always
