---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-key
  namespace: {{.Values.namespace}}
spec:
  encryptedData:
    key: AgAdTJKDQECh1TiZ/+3LrLFLe28SKtgMnHaxIcnIXM/av6CICQIkoRfW50zzT7WiGDcQMhXL8Ii8Oi8IKXWqk/TQP6VFTJSugTJsrj7AVs1qLRh+SMZFwgxUgXBEwvZLbO6QNkZ/MR1PJOQvsaiPfLHbbSLAvf+FhVdK32ZMtli3902Ib9K5/+xFpF7ch/WwyNQ+TirkPTKasRRkcAeVUg5u/mg8hwLQfIuMihsWBkfb9STssiI2S8GGzf0FTUBdN70yf/Tdj2JzGYRKuu8iNOn8SrVS/u17VHfv5EbP16wmSk/SExPex5y6uDnd6TYSAxN8ZixRJFn86xvqPk6R5oNfpvN9ihm1qbU25/Ba0nN0yaPp4b9WNwGpw0d4Am7ARFSHEz/jzckOrHiehG4/ai7ltp6QsYhsSBRzjSvB5J5+SKkdfjC52oJ/WFeEoqbyWYgQNa/K5Fyd45Af7mPuwmfbN2XGHJBQ8CnHM+oxV6RZmdT1Y0vpVM8EUSUFeajzz3z9SYDrkIb0NVljNYl4cOTqqWgxdLiLH3WqdD8TW9ZYOIePfoC2Yy1UFd9wdZFMWtiti4a1FpS9z70Q03bVkV8ZIsa7Ra3nXejtB+2XATVqJgP7SeVOIoo3YlVGeZRSLnohW0hGaW0uQwZcuS8MB1gXmt9L35nwXktiHg5Gh7tJX+0QL3Junhq36uBTgivzZzqFM5v9qmNiazzn4OOL320casJXV37xY+YJRRpV8BfAq8cyLTobOKODSm6lpkgM7zREpa/LAXqW+gjkXk7L6AAFSMklEjwDPwF9O4BtNX+YhkqyWGemKUCFWf2xLW8s8nS7razV8fRkw+5vfzVhUABi0qL5xbY84YBlAyhk8v3MorjI9g==
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: {{ .Values.appName }}
        meta.helm.sh/release-namespace: {{.Values.namespace}}
      creationTimestamp: null
      labels:
        app: {{.Values.appName}}
        app.kubernetes.io/managed-by: Helm
      name: secret-key
      namespace: {{.Values.namespace}}
    type: Opaque
