apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
data:
  SMTP_HOST: "smtp.strato.de"
  SMTP_FROM: "vault@jgdperl.com"
  SMTP_PORT: "587"
  SMTP_SECURITY: "starttls"
  WEBSOCKET_ENABLED: "true"
  DATA_FOLDER: "/data"
  DOMAIN: "https://{{.Values.url}}"
  PUSH_ENABLED: "true"
  SIGNUPS_ALLOWED: "false"
