apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      name: {{ .Values.appName }}
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: vaultwarden/server:raspberry
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /data/
              name: {{ .Values.appName }}-pvc
      volumes:
        - name: {{ .Values.appName }}-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}-pvc
      restartPolicy: Always
      