apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-discovery
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 1900
      targetPort: 1900
  type: LoadBalancer
  