apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-local
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
  type: LoadBalancer
  