apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.appName}}-configmap
data:
  PAPERLESS_URL: "https://docs.jgdperl.com"
  PAPERLESS_USE_X_FORWARD_HOST: "true"
  PAPERLESS_USE_X_FORWARD_PORT: "true"
  PAPERLESS_PROXY_SSL_HEADER: '[ "HTTP_X_FORWARDED_PROTO", "https" ]'
  PAPERLESS_OCR_LANGUAGES: "deu"
  PAPERLESS_TIME_ZONE: "Europe/Berlin"
