apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}
  labels:
    app: {{.Values.appName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      name: {{.Values.appName}}
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
        - name: {{.Values.image.paperless.name}}
          image: {{.Values.image.paperless.repository}}:{{.Values.image.paperless.tag}}
          imagePullPolicy: {{.Values.image.paperless.pullPolicy}}
          ports:
            - containerPort: 8000
              hostPort: 8000
              name: web
          envFrom:
            - configMapRef:
                name: {{.Values.appName}}-configmap
          env:
            - name: PAPERLESS_REDIS
              value: redis://127.0.0.1:6379
            - name: PAPERLESS_TIKA_ENABLED
              value: "1"
            - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
              value: http://127.0.0.1:3000
            - name: PAPERLESS_TIKA_ENDPOINT
              value: http://127.0.0.1:9998
          volumeMounts:
            - mountPath: /usr/src/paperless
              name: paperless-pv
        - name: {{.Values.image.broker.name}}
          image: {{.Values.image.broker.repository}}:{{.Values.image.broker.tag}}
          imagePullPolicy: {{.Values.image.broker.pullPolicy}}
          volumeMounts:
            - mountPath: /data
              name: redisdata
        - name: {{.Values.image.gotenberg.name}}
          image: {{.Values.image.gotenberg.repository}}:{{.Values.image.gotenberg.tag}}
          imagePullPolicy: {{.Values.image.gotenberg.pullPolicy}}
          command:
            - "gotenberg"
            - "--chromium-allow-list=file:///tmp/.*"
        - name: {{.Values.image.tika.name}}
          image: {{.Values.image.tika.repository}}:{{.Values.image.tika.tag}}
          imagePullPolicy: {{.Values.image.tika.pullPolicy}}
      restartPolicy: Always
      volumes:
        - name: redisdata
          emptyDir: {}
        - name: paperless-pv
          persistentVolumeClaim:
            claimName: {{.Values.appName}}-pvc
