{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.hostnames}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.appName }}-{{.name}}-ingress
  namespace: {{ $.Values.appName }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: {{.path}}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ $.Values.appName }}-web
                port:
                  name: web
---
{{- end}}
{{- end}}
