apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.appName}}-config
  labels:
    name: {{.Values.appName}}-config
  namespace: {{.Values.namespace}}
data:
  configuration.yaml: |-
    # Loads default set of integrations. Do not remove.
    default_config:
    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 192.168.178.0/24

    homeassistant:
      unit_system: {{.Values.config.unit_system}}
      name: {{.Values.config.name}}
      external_url: "https://{{.Values.config.baseUrl}}"
      time_zone: {{.Values.config.timezone}}

    homekit:
      - name: {{.Values.config.homekit.name}}
        port: {{.Values.config.homekit.port}}
        advertise_ip: 192.168.178.40
        filter:
          include_entity_globs:
            {{- range .Values.config.homekit.filter.include_entity_globs}}
              - {{ . }}
            {{- end}}
